version: '3'

services:
  nginx:
    container_name: laravel-lab-nginx-alpine
    build:
      context: ./docker/nginx
    ports:
      - 8080:8080
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.crt:/etc/nginx/ssl-certs/nginx.crt
      - ./docker/nginx/nginx.key:/etc/nginx/ssl-certs/nginx.key
      - ./:/usr/share/nginx/html
    depends_on:
      - mysql
  php:
    container_name: laravel-lab-php-alpine
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    user: bimantara
    volumes:
      - ./:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    depends_on:
      - mysql
  mysql:
    container_name: laravel-lab-mysql
    build:
      context: ./docker/mysql
    ports:
      - 3306:3306
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: b1sm1ll4h
      MYSQL_DATABASE: laravel-lab
  redis:
    container_name: laravel-lab-redis
    build:
      context: ./docker/redis
    ports:
      - 6379:6379
  jenkins:
    build:
      context: ./docker/jenkins
    container_name: laravel-lab-jenkins
    ports:
      - 8081:8080
      - 50000:50000
